name: brewmaster_app
description: BrewMaster Pro — ESP32 Bira & Damıtma Kontrol Uygulaması
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State yönetimi
  provider: ^6.1.1

  # WebSocket
  web_socket_channel: ^2.4.0

  # BLE
  flutter_blue_plus: ^1.31.9

  # Ağ
  http: ^1.2.0

  # Yerel depolama (son bağlanan cihaz, ayarlar)
  shared_preferences: ^2.2.2

  # Bildirimler
  flutter_local_notifications: ^17.0.0

  # Grafikler
  fl_chart: ^0.68.0

  # İkonlar
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
